class CanvasConfig:
    NUMBER_ROWS = 4
    NUMBER_COLUMNS = 5

    CPU_POSITION = (1, 4)
    DISK_POSITION_READ = (8, 9)
    DISK_POSITION_WRITE = (6, 7)
    MEMORY_POSITION = (11, 13)
    DISK_PIE_POSITION = 14
    NETWORKING_POSITION_SEND = (18, 19)
    NETWORKING_POSITION_RECEIVE = (16, 17)
    INFORMATION_POSITION = (5, 20)

    MAX_SECONDS_ON_PLOTS = 61

    SEPARATOR_LENGTH = 35
